"""Gemma4 image-path diagrams from native Apache-2.0 Transformers and pinned configs."""
from vlm_native import Diagram,wrap,WEB,SRC,REV,box,chain,mlp_definition
from florence_native import seq
import json
rows=[json.loads(p.read_text()) for p in sorted((WEB/'scripts/model-diagrams/evidence/vlm-configs').glob('gemma4-*.json'))]
def build(r,symbolic=False):
 t=r['config']['text_config'];D='D' if symbolic else t['hidden_size'];N='N' if symbolic else t['num_hidden_layers'];KV='KV' if symbolic else t['num_key_value_heads'];F='F' if symbolic else t['intermediate_size'];first=t['num_hidden_layers']-t['num_kv_shared_layers'];sharedF='Fs' if symbolic else t['intermediate_size']*(2 if t['use_double_wide_mlp'] else 1);name='Gemma4 family' if symbolic else 'Gemma4 '+r['size'].upper()
 d=Diagram(name,'Image detection path. Nominal896px; variable-resolution processor permits up to560 soft image tokens. No audio path is used.',width=2740,height=5070,source_url=f'https://github.com/LibreYOLO/libreyolo/blob/{REV}/{r["source"]}',source_label=r['source']+'; Transformers 5.16.1',revision=REV,logo=WEB/'public/icon-128.png')
 p=d.panel('vision','Vision encoder and projection',40,220,640,1210)
 seq(p,[('pixels','Flatten image patches','P patches; 16 × 16 × 3 =768 values','plain'),('scale','Scale pixels: 2 × (x - 0.5)','Padding patch positions use (-1,-1)','plain'),('patch','Patch Linear','768 to768; no bias','linear'),('pos','Add learned x and y positions','P × 768','plain'),('vstack','Vision encoder layers','16 layers; 12 Q/K/V heads; head width64','attention','vision-layer'),('pool','Spatial average pooling','3 × 3 patches; zero padding before pooling','pool'),('mag','Scale by sqrt(768)','Strip padding tokens; P/9 soft tokens','plain'),('proj','Unscaled RMSNorm; Linear','768 to '+str(D)+'; no bias','linear')],w=440,step=137)
 p=d.panel('fusion','Multimodal sequence and layer inputs',720,220,640,1210)
 seq(p,[('ids','Prompt token embeddings',f'Vocabulary262144; width {D}','linear'),('scaleemb','Scale embeddings',f'Multiply by sqrt({D})','plain'),('replace','Replace image placeholders',f'Projected soft tokens; length L × {D}','concat'),('pli','Construct per-layer input tensors',f'L × {N} × 256; see PLI inset','bottleneck','pli-build'),('sequence','Sequence to decoder','Preserve causal and padding masks','plain')],w=440,step=185)
 p.text(24,1100,'Image embeddings and token IDs both contribute to PLI.',14)
 p.text(24,1140,'Out-of-vocabulary image IDs use the text pad ID for lookup.',13)
 p=d.panel('stack','Text layer schedule and shared K/V',1380,220,640,1210)
 seq(p,[('native','Layers with their own K/V',f'Indices0 to {first-1}' if not symbolic else 'Indices0 to B-1','attention','text-layer'),('save','Keep last full and sliding K/V','Two separate tensors per layer type','plain'),('reuse','Remaining layers reuse K/V',f'Indices{first} to {t["num_hidden_layers"]-1}' if not symbolic else 'IndicesB to N-1','attention','text-layer'),('norm','Final RMSNorm',f'L × {D}','norm'),('lm','Tied vocabulary Linear',f'{D} to262144','linear'),('gen','Greedy autoregressive generation','Thinking disabled by LibreYOLO prompt','plain')],w=440,step=175)
 p.wire([p.port('save','left'),(50,269.5),(50,444.5),p.port('reuse','left')],start='save',end='reuse');p.text(22,1160,'Shared layers still compute their own Q and MLP.',14)
 p=d.panel('adapter','Detection output and exact layer settings',2060,220,640,1210)
 seq(p,[('json','Parse JSON array','box_2d and label fields','plain'),('coord','Convert yxyx to xyxy','Divide 0 to1000 coordinates by1000','plain'),('filter','Filter class, confidence and boxes','Synthetic score1; same-class deduplication','plain'),('result','Results.boxes','Scale to original W,H; cap max_det','plain')],w=440,step=140)
 p.text(24,710,'Sliding layers:512-token window; head width256.',15)
 p.text(24,755,'Full layers:entire prefix; head width512.',15)
 p.text(24,800,'Text Q heads8; K/V heads '+str(KV)+'.',15)
 p.text(24,845,'Base FFN width '+str(F)+'; shared-layer FFN '+str(sharedF)+'.',14)
 full=[i for i,k in enumerate(t['layer_types']) if k=='full_attention']
 p.text(24,900,'Full-attention layer indices (zero-based):',15)
 p.text(24,942,'See E2B/E4B table.' if symbolic else ', '.join(map(str,full)),16)
 p.text(24,1000,'All remaining layers are sliding attention.',15)
 p.text(24,1050,'No expert routing; attention K and V are distinct.',14)
 def layer(id,title,x,y,dim,text=False):
  p=d.panel(id,title,x,y,640,1610,kind='attention',dashed=True,block_type=id)
  box(p,id+'in',70,'Input',f'L × {dim}' if text else 'P × 768',x=180,w=360);prev=id+'in'
  for i,(label,detail,typ) in enumerate([('Attention','Text attention, shared K/V by layer type' if text else 'Image attention with 2D RoPE','text-attn' if text else 'vision-attn'),('Gated MLP',f'Inner width {F} or {sharedF}' if text else 'Inner width3072','text-mlp' if text else 'vision-mlp')]):
   y0=190+i*480;p.dot(360,y0-35)
   box(p,id+'pre'+str(i),y0,'RMSNorm',f'{dim} channels','norm',x=180,w=360);p.connect(prev,id+'pre'+str(i))
   box(p,id+'op'+str(i),y0+110,label,detail,'attention' if i==0 else 'bottleneck',x=180,w=360,typ=typ);p.connect(id+'pre'+str(i),id+'op'+str(i))
   box(p,id+'post'+str(i),y0+220,'RMSNorm',f'{dim} channels','norm',x=180,w=360);p.connect(id+'op'+str(i),id+'post'+str(i))
   p.sum(id+'sum'+str(i),360,y0+350);p.connect(id+'post'+str(i),id+'sum'+str(i));p.wire([(360,y0-35),(60+i*35,y0-35),(60+i*35,y0+350),(347,y0+350)],start=prev,end=id+'sum'+str(i));prev=id+'sum'+str(i)
  if text:
   box(p,'pli-gate',1160,'Per-layer input residual branch',f'256-wide gate; see PLI application inset','bottleneck',x=180,w=360,typ='pli-apply');p.connect(prev,'pli-gate');prev='pli-gate'
   box(p,'layerscale',1300,'Multiply by layer scalar','One stored scalar per layer','plain',x=180,w=360);p.connect(prev,'layerscale');prev='layerscale'
  box(p,id+'out',1470,'Output',f'Width{dim}',x=180,w=360);p.connect(prev,id+'out')
 layer('vision-layer','Vision encoder layer',40,1470,768)
 layer('text-layer','Text decoder layer',720,1470,D,True)
 def attn(id,title,x,y,vision=False,shared=False):
  p=d.panel(id,title,x,y,640,1610,kind='attention',dashed=True,block_type='vision-attn' if vision else 'text-attn')
  hd='64' if vision else '256 local / 512 full';hw='768' if vision else str(D);heads='12' if vision else '8';kv='12' if vision else str(KV)
  p.text(20,65,'Q heads '+heads+'; K/V heads '+kv+'; head width '+hd+'.',14)
  for z,xx in [('q',20),('k',230),('v',440)]:
   lab=z.upper()+' from saved layer' if shared and z!='q' else z.upper()+' Linear'
   box(p,id+z,115,lab,('Already normalized; K has RoPE' if z=='k' else 'Already normalized') if shared and z!='q' else hw+' to '+(heads if z=='q' else kv)+' × head width','plain' if shared and z!='q' else 'linear',x=xx,w=180,h=66)
   if not(shared and z!='q'):
    box(p,id+z+'norm',280,'RMSNorm',('No learned scale' if z=='v' else 'Per-head learned scale'),'norm',x=xx,w=180);p.connect(id+z,id+z+'norm')
    if z!='v':box(p,id+z+'rope',410,'2D RoPE' if vision else 'RoPE',hd+' channels','plain',x=xx,w=180);p.connect(id+z+'norm',id+z+'rope')
  q=id+'qrope';k=id+'k' if shared else id+'krope';vv=id+'v' if shared else id+'vnorm'
  box(p,id+'align',540,'Align K/V to Q heads','Grouped-query head repetition' if not vision else 'Same number of heads','plain',x=230,w=390);p.connect(k,id+'align',via=[(320,500),(345,500)]);p.connect(vv,id+'align',via=[(530,500),(515,500)])
  box(p,id+'qk',710,'Q × transpose(K)','Attention scaling is1.0','attention',x=100,w=380)
  p.wire([p.port(q),(110,660),(215,660),(215,710)],start=q,end=id+'qk');p.wire([p.port(id+'align'),(425,660),(380,660),(380,710)],start=id+'align',end=id+'qk')
  box(p,id+'soft',855,'Masked softmax over keys','Image padding mask' if vision else 'Causal; sliding window512 or full prefix','attention',x=100,w=380);p.connect(id+'qk',id+'soft')
  box(p,id+'av',1000,'Attention weights × V','Weighted sum per query head','attention',x=100,w=380);p.connect(id+'soft',id+'av');p.wire([p.port(id+'align','right'),(630,564.5),(630,1024.5),p.port(id+'av','right')],start=id+'align',end=id+'av')
  box(p,id+'out',1180,'Concat heads; output Linear',heads+' × head width to '+hw,'linear',x=100,w=380);p.connect(id+'av',id+'out')
  p.text(20,1370,'Vision Linear = clamp input, Linear, clamp output.' if vision else 'K/V producer: last nonshared layer of matching type.',14)
  p.text(20,1430,'Clamp bounds come from checkpoint buffers.' if vision else 'Consumers do not own K/V projections or K/V norms.',14)
  p.text(20,1510,'RMSNorm: x / sqrt(mean(x²)+1e-6); learned scale except V.',13)
 attn('vatt','Vision attention primitives',1380,1470,True)
 attn('satt','Text attention with shared K/V',2060,1470,shared=True)
 attn('tatt','Text attention with own K/V',40,3120)
 p=d.panel('pli-build','Per-layer input construction',720,3120,640,1610,kind='bottleneck',dashed=True,block_type='pli-build')
 box(p,'lookup',90,'Token-ID embedding',f'262144 to {N} × 256; scale16','linear',x=25,w=280)
 box(p,'modelproj',90,'Sequence Linear',f'{D} to {N} × 256; scale1/sqrt({D})','linear',x=335,w=280)
 box(p,'reshape-id',270,'Reshape',f'L × {N} × 256','plain',x=25,w=280);p.connect('lookup','reshape-id')
 box(p,'reshape-proj',270,'Reshape',f'L × {N} × 256','plain',x=335,w=280);p.connect('modelproj','reshape-proj')
 box(p,'proj-norm',430,'RMSNorm','256 channels','norm',x=335,w=280);p.connect('reshape-proj','proj-norm')
 p.sum('pli-sum',320,630);p.wire([p.port('reshape-id'),(165,630),(307,630)],start='reshape-id',end='pli-sum');p.wire([p.port('proj-norm'),(475,630),(333,630)],start='proj-norm',end='pli-sum')
 box(p,'pli-scale',760,'Scale by1/sqrt(2)',f'L × {N} × 256','plain',x=100,w=440);p.connect('pli-sum','pli-scale')
 box(p,'pli-select',950,'Select layer index i','L × 256 delivered to decoder layer i','split',x=100,w=440);p.connect('pli-scale','pli-select')
 p.text(24,1120,'Token identity uses original IDs after replacing image-only IDs.',14)
 p.text(24,1170,'The model projection sees the fused image/text embeddings.',14)
 p=d.panel('pli-apply','Per-layer input application',1380,3120,640,1610,kind='bottleneck',dashed=True,block_type='pli-apply')
 seq(p,[('pi','Hidden state after MLP residual',f'L × {D}','plain'),('pg','Gate Linear',f'{D} to256; no bias','linear'),('pa','GELU tanh approximation','256 channels','activation')],x=160,w=420,step=200)
 p.dot(370,160)
 box(p,'pmul',690,'Multiply by layer input','L × 256 from matching layer slice','plain',x=160,w=420);p.connect('pa','pmul')
 box(p,'pproj',890,'Linear',f'256 to {D}; no bias','linear',x=160,w=420);p.connect('pmul','pproj')
 box(p,'pnorm',1090,'RMSNorm',f'{D} channels','norm',x=160,w=420);p.connect('pproj','pnorm')
 p.sum('psum',370,1290);p.connect('pnorm','psum');p.wire([(370,160),(60,160),(60,1290),(357,1290)],start='pi',end='psum')
 box(p,'pout',1430,'Output to layer scalar',f'L × {D}','plain',x=160,w=420);p.connect('psum','pout')
 p=d.panel('gatedmlp','Gated MLP primitives',2060,3120,640,1610,kind='bottleneck',dashed=True,block_type='text-mlp')
 box(p,'mi',80,'Input','Vision width768; text width '+str(D),x=160,w=350);p.dot(335,165)
 box(p,'mg',260,'Gate Linear','Vision3072; text '+str(F)+' / '+str(sharedF),'linear',x=20,w=280)
 box(p,'mu',260,'Up Linear','Same inner width as gate','linear',x=340,w=280)
 p.wire([p.port('mi'),(335,165)],start='mi',arrow=False)
 for id,xx in [('mg',160),('mu',480)]:p.wire([(335,165),(xx,165),(xx,260)],start='mi',end=id)
 box(p,'mgelu',470,'GELU tanh approximation','Elementwise activation','activation',x=20,w=280);p.connect('mg','mgelu')
 box(p,'mmul',710,'Elementwise multiply','Gate activation × up-projection','plain',x=110,w=430)
 p.wire([p.port('mgelu'),(160,655),(225,655),(225,710)],start='mgelu',end='mmul');p.wire([p.port('mu'),(480,655),(425,655),(425,710)],start='mu',end='mmul')
 box(p,'mdown',920,'Down Linear','Inner width to input width','linear',x=110,w=430);p.connect('mmul','mdown')
 p.text(24,1130,'Vision uses clamp/Linear/clamp for all three projections.',14)
 p.text(24,1190,'Text uses ordinary bias-free Linear projections.',14)
 p.text(24,1250,'E2B doubles MLP width only in shared-K/V layers.',14)
 p.text(24,1310,'E4B keeps the same MLP width in every layer.',14)
 # Alias block type on visible panel for vision MLP inspection.
 p.text(24,1390,'This primitive graph defines both vision and text MLPs.',14)
 p=d.panel('table','Concrete text configuration and layer schedule',40,4770,2660,180)
 p.text(20,64,'E2B: D1536, N35, KV1, F6144, Fs12288, B15. Full layers4,9,14,19,24,29,34; all others sliding.',19)
 p.text(20,104,'E4B: D2560, N42, KV2, F10240, Fs10240, B24. Full layers5,11,17,23,29,35,41; all others sliding.',19)
 p.text(20,145,'D=width; N=layers; KV=K/V heads; F=base FFN; Fs=shared-layer FFN; B=first shared layer. Both configurations use PLI width256.',16)
 d.text(50,5000,'Verified from pinned configuration, native forward paths and meta module geometry. No pretrained execution; processor controls actual patch counts.',14)
 ident='family' if symbolic else r['size']+'-detect';out=WEB/'public/diagrams/models/gemma4';out.mkdir(parents=True,exist_ok=True);svg=out/(ident+'.svg');d.save(svg);wrap(svg,out/(ident+'.html'))
 return dict(id=ident,label=name,size='family' if symbolic else r['size'],task='detect',kind='family' if symbolic else 'concrete',svg=f'/diagrams/models/gemma4/{ident}.svg',html=f'/diagrams/models/gemma4/{ident}.html',verification='meta',input='896 nominal; max560 soft tokens')
views=[build(r) for r in rows]+[build(rows[0],True)];out=WEB/'public/diagrams/models/gemma4';(out/'manifest.json').write_text(json.dumps(dict(family='gemma4',slug='gemma4',title='Gemma4',source_revision=REV,default_view=views[0]['id'],views=views),indent=2)+'\n')
(WEB/'scripts/model-diagrams/evidence/gemma4.json').write_text(json.dumps(dict(source_revision=REV,backend='Transformers5.16.1 native Apache-2.0',configs=[{k:r[k] for k in ['repo','resolved_revision','source','meta']} for r in rows],checks=['Native forward-path inspection','Meta constructor dimensions including shared KV and per-layer input'],limits=['Image path only','No pretrained inference','Checkpoint clipping bounds not resolved']),indent=2)+'\n')
print('gemma4 3 views')
