"""Original Kosmos-2 diagram; native Apache Transformers and MIT LibreYOLO adapter."""
from vlm_native import Diagram,wrap,WEB,SRC,REV,box,chain,residual_definition,mlp_definition
from florence_native import seq
import json
r=json.loads((WEB/'scripts/model-diagrams/evidence/vlm-configs/kosmos2-224.json').read_text())
d=Diagram('Kosmos-2 patch14-224','Grounded entity generation. Image 224 × 224; native Transformers image-to-text projection and decoder.',width=2200,height=3710,source_url=f'https://github.com/LibreYOLO/libreyolo/blob/{REV}/{r["source"]}',source_label=r['source']+'; Transformers 5.16.1',revision=REV,logo=WEB/'public/icon-128.png')
p=d.panel('vision','Vision encoder',40,220,650,1000)
seq(p,[('image','Image tensor','1 × 3 × 224 × 224','plain'),('patch','Conv2d patch embedding','3 to 1024; kernel14, stride14; no bias','conv2d'),('cls','Prepend learned CLS','257 × 1024 including 256 patches','concat'),('pos','Add learned absolute positions','257 positions; LayerNorm1024','norm'),('vl','Vision transformer layers','24 layers; 16 heads; head width64','attention','vision-layer'),('ln','Post LayerNorm on all tokens','257 × 1024','norm'),('l2','L2 normalize each token','Divide by channel-vector norm','norm')],w=440,step=130)
p=d.panel('fusion','Latent-query image projection',730,220,700,1000)
box(p,'dense',70,'Linear visual features','1024 to 2048','linear',x=30,w=310)
box(p,'latent',70,'Learned latent queries','64 × 2048','linear',x=380,w=290)
box(p,'concat',240,'Concat features and queries','321 × 2048; source for K and V','concat',x=120,w=460)
p.wire([p.port('dense'),(185,185),(245,185),(245,240)],start='dense',end='concat');p.wire([p.port('latent'),(525,185),(455,185),(455,240)],start='latent',end='concat')
box(p,'cross',400,'Cross-attention projection','Q=64 latent queries; K/V=321 tokens','attention',x=120,w=460,typ='projection-attention');p.connect('concat','cross');p.wire([p.port('latent','right'),(685,94.5),(685,424.5),p.port('cross','right')],start='latent',end='cross')
box(p,'visualtokens',540,'Image embedding sequence','64 × 2048','plain',x=120,w=460);p.connect('cross','visualtokens')
box(p,'text',650,'Embed prompt token IDs','Vocabulary65037; width2048','linear',x=120,w=460)
box(p,'replace',760,'Replace image-token placeholders','Insert64 image embeddings','concat',x=120,w=460);p.connect('text','replace');p.wire([p.port('visualtokens','left'),(50,564.5),(50,784.5),p.port('replace','left')],start='visualtokens',end='replace')
box(p,'positions',880,'Scale by sqrt(2048); add positions','Sinusoidal text positions; sequence L × 2048','plain',x=120,w=460);p.connect('replace','positions')
p=d.panel('language','Language decoder and adapter',1470,220,690,1000)
seq(p,[('textlayers','Causal text transformer layers','24 layers; 32 heads; head width64','attention','text-layer'),('finalnorm','Final LayerNorm','L × 2048','norm'),('logits','Tied vocabulary Linear','2048 to65037; greedy token selection','linear'),('decode','Processor decodes grounded entities','Names, spans, normalized xyxy boxes','plain'),('match','Match entity names to classes','Exact or substring match; requested classes','plain'),('filter','Filter boxes and synthetic score1','Reject nonpositive area; cap max_det','plain'),('pixels','Results.boxes','Scale x by original W and y by original H','plain')],w=470,step=130)
residual_definition(d,'vision-layer','Vision transformer layer',40,1260,1024,'Vision attention','Vision MLP','LayerNorm')
residual_definition(d,'text-layer','Text transformer layer',590,1260,2048,'Text attention','Text MLP','LayerNorm')
def attn(id,title,x,y,width,heads,inner=False,projection=False):
 p=d.panel(id,title,x,y,510,1050,kind='attention',dashed=True,block_type=id)
 for z,xx in [('q',15),('k',182),('v',349)]:box(p,id+z,80,z.upper()+' Linear',f'{width} to {width}','linear',x=xx,w=146)
 p.text(20,175,'Q: latent queries; K/V: features + queries.' if projection else 'Q/K/V from the same normalized input.',13)
 box(p,id+'split',220,'Split into heads',f'{heads} heads × 64 channels','split',x=50,w=410)
 for z in ['q','k','v']:p.connect(id+z,id+'split',via=[(88 if z=='q' else 255 if z=='k' else 422,195)])
 box(p,id+'qk',345,'Q × transpose(K)','Scale1/sqrt(64)','attention',x=50,w=300);p.connect(id+'split',id+'qk',via=[(255,305),(200,305)])
 box(p,id+'soft',460,'Softmax over keys','Causal/padding mask' if inner else 'All source tokens','attention',x=50,w=300);p.connect(id+'qk',id+'soft')
 box(p,id+'av',580,'Attention weights × V','Per-head weighted value sum','attention',x=50,w=360);p.connect(id+'soft',id+'av',via=[(200,550),(230,550)])
 p.wire([p.port(id+'split','right'),(485,244.5),(485,604.5),p.port(id+'av','right')],start=id+'split',end=id+'av')
 box(p,id+'join',700,'Concat heads',f'Width{width}','concat',x=50,w=360);p.connect(id+'av',id+'join');last=id+'join'
 if inner:box(p,id+'inner',800,'Inner attention LayerNorm','2048 channels','norm',x=50,w=360);p.connect(last,id+'inner');last=id+'inner'
 box(p,id+'out',920,'Output Linear',f'{width} to {width}','linear',x=50,w=360);p.connect(last,id+'out')
 return p
attn('vision-attn','Vision attention',1140,1260,1024,16)
attn('text-attn','Text attention with inner normalization',1690,1260,2048,32,inner=True)
attn('projection-attention','Projection attention',40,2360,2048,32,projection=True)
mlp_definition(d,'vision-mlp','Vision MLP',590,2360,1024,4096,'QuickGELU',False)
p=d.panel('text-mlp','Text MLP with inner normalization',1140,2360,510,1050,kind='bottleneck',dashed=True,block_type='text-mlp')
seq(p,[('fc1','Linear','2048 to8192','linear'),('gelu','GELU','Elementwise activation','activation'),('innernorm','Inner FFN LayerNorm','8192 channels','norm'),('fc2','Linear','8192 to2048','linear')],x=65,w=380,start=90,step=210)
p=d.panel('scope','Execution and tensor scope',1690,2360,510,1050)
for i,s in enumerate(['One released 224-pixel configuration.','Image tokens:257 before the projector.','Image embeddings:64 after the projector.','Text length L is runtime dependent.','No language cross-attention layers.','Image features enter via placeholders.','Dropout disabled in inference.','Cached generation reuses text K/V.','QuickGELU: x × sigmoid(1.702 × x).','Source/config and meta checks only.','No pretrained output was evaluated.']):p.text(20,95+i*73,s,15)
d.text(50,3600,'Sources: pinned microsoft/kosmos-2-patch14-224 config; native Transformers 5.16.1 Kosmos2 classes; LibreYOLO output adapter.',14)
out=WEB/'public/diagrams/models/kosmos-2';out.mkdir(parents=True,exist_ok=True);svg=out/'224-detect.svg';d.save(svg);wrap(svg,out/'224-detect.html')
(out/'manifest.json').write_text(json.dumps(dict(family='kosmos2',slug='kosmos-2',title='Kosmos-2',source_revision=REV,default_view='224-detect',views=[dict(id='224-detect',label='Kosmos-2 patch14-224',size='224',task='detect',kind='concrete',svg='/diagrams/models/kosmos-2/224-detect.svg',html='/diagrams/models/kosmos-2/224-detect.html',verification='meta',input='224 × 224')]),indent=2)+'\n')
(WEB/'scripts/model-diagrams/evidence/kosmos2.json').write_text(json.dumps(dict(source_revision=REV,backend='Transformers5.16.1 native Apache-2.0',config={k:r[k] for k in ['repo','resolved_revision','source','meta']},checks=['Native forward-path inspection','Meta constructor dimensions'],limits=['No pretrained inference']),indent=2)+'\n')
print('kosmos2 1 view')
